//
//  ListPresenterTests.swift
//  ListApp
//
//  Created by Satya on 07/11/20.
//  Copyright (c) 2020 Satya. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ListApp
import XCTest

class ListPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListPresenter()
  {
    sut = ListPresenter()
  }
  
  // MARK: Test doubles
  
  class ListDisplayLogicSpy: ListDisplayLogic
  {
    var displayApiListeItemsCalled = false
    
    func displayApiListeItemsResponse(viewModel: [List.APIList.ViewModel])
    {
      displayApiListeItemsCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentWithListitemsApiResonse()
  {
    // Given
    let spy = ListDisplayLogicSpy()
    sut.viewController = spy
    let response = List.APIList.Response()
    
    // When
    sut.presentWithListitemsApiResonse(response: response)
    
    // Then
    XCTAssertTrue(spy.displayApiListeItemsCalled, "presentWithListitemsApiResonse(response:) should ask the view controller to display the result")
  }
}
