//
//  ListWorkerTests.swift
//  ListApp
//
//  Created by Satya on 07/11/20.
//  Copyright (c) 2020 Satya. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ListApp
import XCTest

class ListWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListWorker()
  {
    sut = ListWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testSomething()
  {
    // Given
    
    let request = List.APIList.Request()
    
    // When
    sut.fetchListViewItems(request) { (response) in
        // Then
        XCTAssertTrue(response != nil, "Api items fetched successfully.")
    }
    
   
  }
}
