//
//  ListInteractorTests.swift
//  ListApp
//
//  Created by Satya on 07/11/20.
//  Copyright (c) 2020 Satya. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ListApp
import XCTest

class ListInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListInteractor()
  {
    sut = ListInteractor()
  }
  
  // MARK: Test doubles
  
  class ListPresentationLogicSpy: ListPresentationLogic
  {
    var presentWithListitemsApiResonseCalled = false
    
    func presentWithListitemsApiResonse(response: List.APIList.Response)
    {
      presentWithListitemsApiResonseCalled = true
    }
  }
  
  // MARK: Tests
  
  func testFetchListItemsApi()
  {
    // Given
    let spy = ListPresentationLogicSpy()
    sut.presenter = spy
    let request = List.APIList.Request()
    
    // When
    sut.fetchApiListitems(request: request, isFromTestCase: true)
    
    // Then
    XCTAssertTrue(spy.presentWithListitemsApiResonseCalled, "fetchApiListitems(request:) should ask the presenter to format the result")
  }
}
