//
//  ListPresenter.swift
//  ListApp
//
//  Created by Satya on 06/11/20.
//  Copyright (c) 2020 Satya. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic
{
  func presentWithListitemsApiResonse(response: List.APIList.Response)
}

class ListPresenter: ListPresentationLogic
{
    weak var viewController: ListDisplayLogic?
    
    // MARK: Present Api list items
    
    func presentWithListitemsApiResonse(response: List.APIList.Response)
    {
        
        DispatchQueue.main.async {
            (self.viewController as? UIViewController)?.navigationItem.title = response.title ?? ""
        }
        viewController?.displayApiListeItemsResponse(viewModel: response.rows ?? [List.APIList.ViewModel]())
    }
}
