//
//  ListWorker.swift
//  ListApp
//
//  Created by Satya on 06/11/20.
//  Copyright (c) 2020 Satya. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListWorker
{
  func doSomeWork()
  {
  }
}
