//
//  ListModels.swift
//  ListApp
//
//  Created by Satya on 06/11/20.
//  Copyright (c) 2020 Satya. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum List
{
  // MARK: Use cases
  
  enum APIList
  {
    struct Request: Encodable
    {
    }
    struct Response: Codable
    {
        var title: String?
        
        var rows: [ViewModel]?
    }
    struct ViewModel: Codable
    {
        var title: String?
        var description: String?
        var imageHref: String?
        
        
    }
  }
}
